[package]
name = "gstream-scratch"
version = "0.1.0"
authors = ["Joshua Gevirtz <joshgev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer-video = "0.15.1"
gstreamer = "0.15.1"
